on: [push, pull_request]
name: osx-ci
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        ghc: ['8.8', '8.10', '9']
    name: Haskell GHC ${{ matrix.ghc }} sample
    env:
        CONFIG: "--enable-tests --enable-benchmarks --test-show-details=direct"
    steps:
      - name: CPU info
        run: |
            sysctl -n machdep.cpu.features
            sysctl -n machdep.cpu.leaf7_features

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Haskell
        run: |
          brew install ghc@${{ matrix.ghc }} cabal-install

      - run: |
          cabal update
          cabal freeze

      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - run: |
          cabal clean # we need force configure to get botan_all.cpp
          cabal configure $CONFIG
          cabal build 
      - run: |
          cabal test
      - run: |
          cabal haddock
          cabal check
          cabal sdist
