on: [push, pull_request]
name: ubuntu-ci
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ghc: ['8.8', '8.10', '9.0']
        cabal: ['3.4']
        exclude:
    name: Haskell GHC ${{ matrix.ghc }} sample
    env:
        CONFIG: "--enable-tests --enable-benchmarks"
        BOTAN_FFI_PRINT_EXCEPTIONS: "1"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - run: cabal v2-update
      - run: cabal v2-freeze $CONFIG
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-

      - run: cabal v2-configure $CONFIG
      - run: cabal v2-build $CONFIG
      - run: cabal v2-test --test-show-details=direct
      - run: cabal v2-haddock
      - run: cabal v2-sdist
