on: [push, pull_request]
name: ubuntu-ci
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ghc: ['8.8.4', '8.10.4', '9.0.1']
        cabal: ['3.2', '3.4']
        exclude:
          # GHC 9+ only works with cabal v3.4+
          - ghc: 9.0
            cabal: 3.2
    name: Haskell GHC ${{ matrix.ghc }} sample
    env:
        CONFIG: "--enable-tests --enable-benchmarks --test-show-details=direct"
    steps:

      - name: CPU info
        run: |
            sudo apt-get install cpuid
            cpuid

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Haskell
        run: |
          sudo add-apt-repository -y -u ppa:hvr/ghc
          sudo apt-get update
          sudo apt-get install ghc-${{ matrix.ghc }} cabal-install-${{ matrix.cabal }}

      - run: |
          cabal update
          cabal freeze 

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - run: |
          cabal clean # we need force configure to get botan_all.cpp
          cabal configure $CONFIG  
          cabal build
      - run: |
          cabal test 
      - run: |
          cabal haddock
          cabal check
          cabal sdist
